config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "articles#index"
  get "welcome/contactos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :cargar_registros
  def cargar_registros
    @categorias = Category.all
    #code
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new()
    respond_to do |format|
      if  @article.save
          format.html {redirect_to @article, notice: "Articulo #{@article.title} Creado"}
          format.json {render :show, status: :created, location: @article}
      else
          format.html {redirect_to :new}
          format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  def show

  end

  def index
    @articulos = Article.all

  end

  def edit

  end
  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit

    end
  end
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Articulo Eliminado"

  end
  private
  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      #raise params.to_yaml
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articulos = Article.all
  end
  def contactos
    @email = "adrian.chaves@gmail.com"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_formulario.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="jumbotron">
        <form>
          <fieldset>

            <legend><%= "#{titulo} Articulo"%></legend>

            <%= form_with(model: @article) do |form| %>
            <div class="form-group">

            <%= form.label "Titulo", class:"col-md-6 col-form-label" %>
            <%= form.text_field :title, class:"col-md-6 form-control" %>
          </div>
            <div class="form-group">

            <%= form.label "Cuerpo", class:"col-md-6 col-form-label" %>
            <%= form.text_field :body , class:"col-md-6 form-control"%>
          </div>
            <div class="form-group">

            <%= form.submit "OK", class:"btn btn-info" %>
            <%= link_to "Atras", articles_path, class:"btn btn-info" %>
          </div>
            <% end %>
          </fieldset>
        </form>

      </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render "formulario", article: @article, titulo: "Editar" %>

app/views/articles/index.html.erb
<div class="row">
  <% @articulos.each do |articulo| %>
    <div class="">
      <div class="jumbotron">

        <h1><%= link_to articulo.title, articulo %></h1>
        <h1><%=articulo.body%></h1>
        <%= link_to "Editar", edit_article_path(articulo), class:"btn btn-info "%>
        <%= link_to "Eliminar #{articulo.title}", articulo, method: :delete,
        data: {confirm:"Seguro?"}, class:"btn btn-info"%>

        </div>
      </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p><%= render "partials/notificaciones.html"  %></p>
<p>Find me in app/views/articles/new.html.erb</p>
<%= render "formulario", article: @article, titulo: "Nuevo  " %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<%= render "partials/notificaciones.html"  %>
<div class="jumbotron">


<%= @article.inspect%>
<h1><%=@article.title%></h1>
<p><%=@article.body%></p>
<%= link_to "Editar", edit_article_path(@article), class:"btn btn-success" %>
<%= link_to "Atras", root_path, class:"btn btn-success" %>
</div>

app/views/categories/_category.html.erb
<style type="text/css" media="screen">
  <%= ".#{category.name}" %> {
    background: <%= category.color %> !important;
  }
</style>

<div class="col-md-3">
  <div class="jumbotron <%= "#{category.name}" %> ">
    <%= category.name %>

  </div>
</div>

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="jumbotron">

          <fieldset>

            <h1><%="#{title} categoria"%></h1>
            <%= form_with(model: category, local: true) do |form| %>
              <% if category.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

                  <ul>
                  <% category.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :name, class:"col-md-6 col-form-label" %>
                <%= form.text_field :name, class: "col-md-6 form-control" %>
              </div>

              <div class="field">
                <%= form.label :color,class: "col-md-6 col-form-label"%>
                <%= form.color_field :color, id: :category_color, class: "col-md-6 form-control" %>
              </div>

              <div class="actions">
                <%= form.submit %>
              </div>
              <%= link_to 'Show', @category %> |
              <%= link_to 'Back', categories_path %>

            <% end %>
          </fieldset>

      </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category, title: "Editar" %>

app/views/categories/index.html.erb
<div class="row">
   <%= render @categories %>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category, title: "Nueva" %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<style media="screen">
  .jumbotron{
    background: <%=@category.color %> !important;
  }
</style>
<div class="jumbotron">


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "partials/navbar" %>
    <div class="row">
        <div class="col-md-2">
          <%= render "partials/panel" %>

        </div>
        <div class="col">
          <%= yield %>

        </div>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Inicio", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contacto", welcome_contactos_path, class:"nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" placeholder="Search" type="text">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/partials/_notificaciones.html.erb
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4 class="alert-heading">Warning!</h4>
  <p class="mb-0">Best check yo self, you're not looking too good. Nulla vitae elit libero, a pharetra augue. Praesent commodo cursus magna, <a href="#" class="alert-link">vel scelerisque nisl consectetur et</a>.</p>

<% if !notice.nil? %>
  <div class="alert alert-dismissible alert-info">
    <p><%= notice %></p>
  </div>
<%end%>
<% if !alert.nil? %>
  <div class="alert alert-dismissible alert-warning">
    <p><%= alert %></p>
  </div>
<%end%>

app/views/partials/_panel.html.erb
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    Categoria
  </a>
  <% @categorias.each do |categoria| %>
  <%= link_to categoria.name, categoria, class:"list-group-item list-group-item-action"%>
  <% end %>
</div>

app/views/welcome/contactos.html.erb
<div class="row">
  <div class="col-md-8 color-c">

        <p>CATALINA .</p>

  </div>
  <div class="col-md-4 color-c">

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>
  <div class="col-md-2 color-b">

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>
  <div class="col-md-2 color-b">

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>

</div>

app/views/welcome/index.html.erb
  <%= link_to "Articles", articles_path %>
<%@articulos.each do |art|%>
  <div class="jumbotron color-b">
    <h2 class="text-center">
    <%= link_to art.title, art %>
    </h2>
  </div>
  <p><%= art.body %></p>
<%end%>